### PR TITLE
Make a package installable + add CI pipelines

### LINKED ISSUE #6: Make a package release
Hi @PierreColombo,

First of all, I'd like to thank you for the great work of you and your team in developing NLG metrics. I'm just curious if you'd be interested in my contribution to creating `setup.py` file and preparing other related stuff so that the repo can be installed from the source with `pip` and also make it potentially published via `pypi`. I believe this could help further adopt your evaluation metrics and make them easier to use for various use cases. Also, we would like to implement these metrics within [`torchmetrics`](https://github.com/PyTorchLightning/metrics) package (see [InfoLM](https://github.com/PyTorchLightning/metrics/issues/849), [BaryScore](https://github.com/PyTorchLightning/metrics/issues/852) and [DepthScore](https://github.com/PyTorchLightning/metrics/issues/854) issues), therefore, the possibility of installing the package from `pypi` would facilitate us to test our implementation against yours so that we can be sure our implementation is correct.

Thanks once again and please let me know what you do think about my proposal :]

cc: @Borda

### PR DESCRIPTION
**Pull request by stancld**
## What does this PR do?

Fixes #6 

This PR updates the structure of this repo and adds some necessary components to make this package easily installable from the source. Furthermore, it defines some CI jobs checking the package and also handling publishing the package distribution to PyPI once a package version is released.

<hr>

@PierreColombo - Could I kindly ask you to check the author information? I'm not really sure if I set these properly. Also, could you please confirm for me that the dependency versions (in `requirements.txt`) make sense w.r.t. your setup?

@Borda - Could I kindly ask you to have quick a look at the changes I made so that we will be sure that everything is alright and the package will be ready soon as a reference one for `torchmetrics` testing? :] (Not sure if there's anything missing)

### CODE REVIEW

**Comment by PierreColombo** [comment]
Hi ! @stancld 
Tell me when it's ready i'll merge it :)

**Comment by stancld** [comment]
Hi @PierreColombo, I'd like to deeply apologize for my delay. I was a bit busy during the last weeks. I'm gonna try to finish this PR this weekend. Thanks a lot for your understanding O:]

**Comment by Borda** [comment]
Yeah, will check it... Somehow missed this notification :(
Cc: @aniketmaurya @SkafteNicki

**Comment by stancld** [comment]
@PierreColombo - Also, in order for package releasing work fine, you'll be required to create [PyPI](https://pypi.org/) access tokens and save them in the repository secrets.

**Comment by vmkhlv** [comment]
Hi @stancld @PierreColombo 
are there any updates on the package release/providing dependencies?

This would be very useful for the community. Thank you

**Comment by stancld** [comment]
Hi @vmkhlv, unfortunately, I have no update here. If you want to, you can give it a try to [`torchmetrics`](https://github.com/Lightning-AI/metrics).  New release `v0.10` should be available in 2 weeks or so and it will contain `InfoLM` metrics. We will try to add remaining two metrics for the next release. You can already install the package from the source to have `InfoLM` available :]

**Comment by vmkhlv** [comment]
@stancld Thank you for reaching out and for your work. Sure, if I have time, I will contact you. Thank you again for your contributions.

**Comment by PierreColombo** [comment]
Hi @stancld @Borda @vmkhlv ! 
Thanks a lot.

**Pull request merged**
